"""Gemini AI client for generating content using Google's GenAI SDK."""

import os
from typing import Optional
from pydantic import BaseModel, Field
from google import genai
from google.genai import types

class GeminiRequest(BaseModel):
    """Request model for Gemini API calls."""
    prompt: str = Field(..., description="The prompt to send to Gemini")
    max_tokens: Optional[int] = Field(default=4000, description="Maximum number of tokens to generate")
    temperature: Optional[float] = Field(default=0.7, description="Sampling temperature (0.0 to 1.0)")


class GeminiResponse(BaseModel):
    """Response model from Gemini API."""
    content: str = Field(..., description="Generated text content")


class GeminiClient:
    """Client for interacting with Google's Gemini API using the SDK."""

    def __init__(self, api_key: str, model_name: str = "gemini-2.0-flash-exp"):
        """
        Initialize Gemini client.

        Args:
            api_key: Google AI API key
            model_name: Gemini model to use (default: gemini-2.0-flash-exp)
        """
        if not api_key:
            raise ValueError("Gemini API key is required")

        self.api_key = api_key
        self.model_name = model_name
        # Initialize the client with the API key
        self.client = genai.Client(api_key=self.api_key)

    async def generate_content(self, request: GeminiRequest) -> GeminiResponse:
        """
        Generate content using Gemini SDK.

        Args:
            request: GeminiRequest with prompt and configuration

        Returns:
            GeminiResponse with generated content

        Raises:
            Exception: If API call fails
        """
        try:
            print(f"Generating content with model: {self.model_name}")
            
            # The SDK supports async calls, but the basic example is synchronous. 
            # We'll use the async version if available or wrap it.
            # Looking at the user snippet: response = client.models.generate_content(...)
            # For async, it's usually client.aio.models.generate_content
            
            response = await self.client.aio.models.generate_content(
                model=self.model_name,
                contents=request.prompt,
                config=types.GenerateContentConfig(
                    max_output_tokens=request.max_tokens,
                    temperature=request.temperature
                )
            )

            if not response.text:
                raise Exception("No content generated by Gemini")

            return GeminiResponse(content=response.text)

        except Exception as error:
            print(f"Gemini SDK Error: {error}")
            raise Exception(f"Gemini SDK call failed: {str(error)}")
